name: heom
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2020.1.
  - certifi=2019.11.28
  - cycler=0.10.0
  - cython=0.29.14
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fastcache=1.1.0
  - flake8=3.7.9
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.63.1
  - gmp=6.1.2
  - gmpy2=2.0.8
  - icu=58.2
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.10.2
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libpng=1.6.37
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.1.0
  - nbconvert=5.6.1
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.2
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1
  - packaging=19.2
  - pandoc=2.2.3.
  - pandocfilters=1.4.2
  - parso=0.5.2
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - pluggy=0.13.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - py=1.8.0
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pyparsing=2.4.5
  - pyqt=5.9.2
  - pyrsistent=0.15.6
  - pytest=5.3.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.6.0
  - qutip=4.4.1
  - readline=7.0
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=42.0.2
  - sip=4.19.8
  - six=1.13.0
  - sqlite=3.30.1
  - sympy=1.5.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11

